/**
 * The Detailed look: our own models (generated by tools/build-models.mjs), fetched on demand. The
 * caches are per mount: one createModels() per engine, cleared on unmount. Nothing here runs in the
 * Low poly look. Each <name>.glb under HERO_MODEL_DIR is fetched at most once and parsed with
 * three's GLTFLoader, which is imported only here and only on the first Detailed request, so it
 * ships as its own chunk. A model becomes plain geometry with a colour per vertex and normals
 * rebuilt with a crease, drawn with the materials the Low poly stand-in already uses, so swapping
 * one in compiles no new shader. A failed fetch or parse rejects; the engine then falls back to
 * Low poly.
 */
import * as THREE from "three";
import type { TrackId } from "../data/types";
import type { CarId } from "./cars";
import type { LpCarModel } from "./scenery/car";

/**
 * Where the models are served from: public/hero/models/. Nothing else names the directory.
 */
export const HERO_MODEL_DIR = "/hero/models/";

export const D_FALLBACK = "Detailed models did not load: showing Low poly";

// ================= The registry =================
// Which of our models stands in for each Low poly type. Trees are per circuit: where two are named,
// stands along the lap alternate between them (the miniature uses the first). Buildings and
// grandstands are the real OSM footprints in both looks; Detailed adds detail on them.
export const DETAILED = {
  trees: {
    spa: { pineForest: ["tree-spruce", "tree-fir"], broadleaf: ["tree-broadleaf"] },
    sebring: { palm: ["tree-palm"], liveOak: ["tree-live-oak"], slashPine: ["tree-slash-pine"] },
    fuji: { pineForest: ["tree-cedar"], cedar: ["tree-cedar"], broadleaf: ["tree-broadleaf"], cherryTree: ["tree-cherry"] },
  } as Record<TrackId, Record<string, string[]>>,
  furniture: { gantry: "gantry", marshalPost: "marshal-post", brakeBoard: "brake-board", armco: "armco", tyreWall: "tyre-wall" } as Record<string, string>,
  mountainFuji: "mountain-fuji",
};
// Fuji is the only circuit whose landmarks include the mountain, and the only one with a
// ground.mount; the list is fixed here so it can be built before the circuit's data has loaded.
const HAS_MOUNTAIN: Record<TrackId, boolean> = { spa: false, sebring: false, fuji: true };

/** Every model the Detailed look needs for this circuit and car: nothing else is fetched. */
export function detailedModels(trackId: TrackId, carId: CarId): string[] {
  const trees = Object.values(DETAILED.trees[trackId] || {}).flat();
  return [...new Set([carId, ...trees, ...Object.values(DETAILED.furniture), ...(HAS_MOUNTAIN[trackId] ? [DETAILED.mountainFuji] : [])])];
}
/** The model for a Low poly tree type at a circuit (variant k of its stands), or null. */
export const detailedTree = (trackId: TrackId, type: string, k = 0): string | null => { const l = (DETAILED.trees[trackId] || {})[type]; return l ? l[k % l.length] : null; };

// ================= Geometry =================
/**
 * Normals for a triangle soup (9 numbers a triangle), smooth across edges where the faces meet at
 * under crease radians, crisp where they fold further: bevels and tyres read round, panel edges sharp.
 */
export function dCrease(pos: Float32Array, crease = 0.7): Float32Array {
  const n = pos.length / 9, fn = new Float32Array(n * 3), un = new Float32Array(n * 3), out = new Float32Array(pos.length), at = new Map<string, number[]>(), lim = Math.cos(crease);
  for (let f = 0; f < n; f++) {
    const o = f * 9, ux = pos[o + 3] - pos[o], uy = pos[o + 4] - pos[o + 1], uz = pos[o + 5] - pos[o + 2], vx = pos[o + 6] - pos[o], vy = pos[o + 7] - pos[o + 1], vz = pos[o + 8] - pos[o + 2];
    const x = uy * vz - uz * vy, y = uz * vx - ux * vz, z = ux * vy - uy * vx, l = Math.hypot(x, y, z) || 1;
    fn.set([x, y, z], f * 3); un.set([x / l, y / l, z / l], f * 3);
  }
  for (let v = 0; v < n * 3; v++) { const k = `${Math.round(pos[v * 3] * 1e4)},${Math.round(pos[v * 3 + 1] * 1e4)},${Math.round(pos[v * 3 + 2] * 1e4)}`; let l = at.get(k); if (!l) at.set(k, (l = [])); l.push(v); }
  for (const list of at.values()) for (const v of list) {
    const f = (v / 3) | 0; let x = 0, y = 0, z = 0;
    for (const w of list) { const g = (w / 3) | 0; if (un[f * 3] * un[g * 3] + un[f * 3 + 1] * un[g * 3 + 1] + un[f * 3 + 2] * un[g * 3 + 2] >= lim) { x += fn[g * 3]; y += fn[g * 3 + 1]; z += fn[g * 3 + 2]; } }
    const l = Math.hypot(x, y, z) || 1; out.set([x / l, y / l, z / l], v * 3);
  }
  return out;
}

type ColoredMaterial = THREE.Material & { color: THREE.Color };
interface GeoOpts {
  /** Leaves these meshes out. */
  skip?: (mesh: THREE.Mesh) => boolean;
  /** A matrix applied after an object's own placement (the gantry's posts and beam), or null. */
  at?: (o: THREE.Object3D) => THREE.Matrix4 | null;
  /** Where shading turns crisp, in radians. */
  crease?: number;
}
/**
 * Everything drawn under node, as one non-indexed geometry in frame's space (node's own by default),
 * each vertex coloured by its material.
 */
export function dGeo(node: THREE.Object3D, opts: GeoOpts = {}, frame: THREE.Object3D = node): THREE.BufferGeometry {
  frame.updateMatrixWorld(true);
  const inv = new THREE.Matrix4().copy(frame.matrixWorld).invert(), m = new THREE.Matrix4(), v = new THREE.Vector3(), pos: number[] = [], col: number[] = [];
  node.traverse((o) => {
    const mesh = o as THREE.Mesh;
    if (!mesh.isMesh || (opts.skip && opts.skip(mesh))) return;
    m.multiplyMatrices(inv, mesh.matrixWorld);
    if (opts.at) for (let a: THREE.Object3D | null = mesh; a && a !== frame; a = a.parent) { const t = opts.at(a); if (t) { m.premultiply(t); break; } }
    const g = mesh.geometry, p = g.attributes.position as THREE.BufferAttribute, idx = g.index, n = idx ? idx.count : p.count, c = (mesh.material as ColoredMaterial).color;
    const flipped = m.determinant() < 0;
    for (let i = 0; i < n; i++) {
      const j = flipped ? i - (i % 3) + [0, 2, 1][i % 3] : i, k = idx ? idx.getX(j) : j;
      v.fromBufferAttribute(p, k).applyMatrix4(m); pos.push(v.x, v.y, v.z); col.push(c.r, c.g, c.b);
    }
  });
  const g = new THREE.BufferGeometry(), P = new Float32Array(pos);
  g.setAttribute("position", new THREE.BufferAttribute(P, 3)); g.setAttribute("normal", new THREE.BufferAttribute(dCrease(P, opts.crease), 3)); g.setAttribute("color", new THREE.Float32BufferAttribute(col, 3));
  g.computeBoundingSphere(); return g;
}
/** Whether o is inside the subtree of any of nodes. */
const dUnder = (o: THREE.Object3D, nodes: THREE.Object3D[]) => { for (let a: THREE.Object3D | null = o; a; a = a.parent) if (nodes.includes(a)) return true; return false; };

const WHEEL_NAMES = ["wheel-fl", "wheel-fr", "wheel-rl", "wheel-rr"];
/** A car's parts, in the Low poly car's units: body without glass, glass, and per wheel its hub and geometry. */
export interface CarParts {
  body: THREE.BufferGeometry;
  glass: THREE.BufferGeometry;
  /** Per wheel node: its hub (x, z), its radius r (the hub's height: the wheels stand on y 0), its geometry. */
  wheels: Record<string, { x: number; r: number; z: number; geo: THREE.BufferGeometry }>;
}

/** Gives a mesh a model's geometry, keeping its Low poly stand-in for dRevert (bounds redone for culling). */
export function dFit(mesh: THREE.Mesh, geo: THREE.BufferGeometry): void {
  if (!mesh.userData.standIn) mesh.userData.standIn = mesh.geometry;
  mesh.geometry = geo; mesh.userData.look = "detailed";
  const im = mesh as THREE.InstancedMesh;
  if (im.isInstancedMesh) { im.boundingSphere = null; im.computeBoundingSphere(); }
}
/** Puts back every stand-in under root, and hides what only the models showed (the models failed). */
export function dRevert(root: THREE.Object3D): void {
  root.traverse((o) => {
    const mesh = o as THREE.Mesh, ud = o.userData;
    if (ud.standIn) {
      mesh.geometry = ud.standIn as THREE.BufferGeometry; delete ud.standIn;
      const im = o as THREE.InstancedMesh;
      if (im.isInstancedMesh) { im.boundingSphere = null; im.computeBoundingSphere(); }
      if (ud.revertHidden) o.visible = false;
    }
    // dFitCar also moves the wheel pivot and rewrites the wheel record's own ride height and radius,
    // none of which is geometry: put those back from the same stash.
    if (ud.standInWheel) {
      const s = ud.standInWheel as { x: number; y: number; z: number; wy: number; wr: number };
      o.position.set(s.x, s.y, s.z);
      if (ud.wheelRef) { ud.wheelRef.y = s.wy; ud.wheelRef.r = s.wr; }
      delete ud.standInWheel;
    }
    if (ud.look === "detailed") ud.look = "lowpoly";
  });
}
/** Puts a model's parts into a car lpCar built, in place: same frame and scale, wheels on their hubs. */
export function dFitCar(car: LpCarModel, parts: CarParts): void {
  dFit(car.body, parts.body); dFit(car.glass, parts.glass); car.glass.visible = true; car.glass.userData.revertHidden = true;
  for (const [name, w] of Object.entries(car.wheels)) {
    const p = parts.wheels[name];
    // Stash the Low poly pivot and the wheel record's own y and r once, before the first fit.
    if (!w.pivot.userData.standInWheel) w.pivot.userData.standInWheel = { x: w.pivot.position.x, y: w.pivot.position.y, z: w.pivot.position.z, wy: w.y, wr: w.r };
    w.pivot.position.set(p.x, p.r, p.z); w.y = p.r; w.r = p.r * car.S; dFit(w.spin, p.geo);
  }
  car.root.userData.look = "detailed";
}

// ================= Loading, once per model per mount =================
/**
 * One piece of scenery waiting for its model: which model, how to fetch its geometry, and how to fit
 * it in place of the Low poly stand-in.
 */
export interface Swap {
  model: string;
  get: () => Promise<THREE.BufferGeometry>;
  fit: (g: THREE.BufferGeometry) => void;
}
/** Building the Detailed look: the circuit (for its tree species) and where its models come from. */
export interface Detail {
  trackId: TrackId;
  src: ModelSource;
}
/** What the scenery asks the Detailed look for; each resolves to geometry (or rejects on failure). */
export interface ModelSource {
  tree(name: string): Promise<THREE.BufferGeometry>;
  furniture(name: string): Promise<THREE.BufferGeometry>;
  mountain(): Promise<THREE.BufferGeometry>;
  /** The start gantry for posts at x = +-X (gantry units): posts moved out, the truss beam stretched to meet them. */
  gantry(X: number): Promise<THREE.BufferGeometry>;
}
export interface Models extends ModelSource {
  /** The parsed scene of <name>.glb, fetched once however often it is asked for. */
  load(name: string): Promise<THREE.Object3D>;
  carParts(id: CarId): Promise<CarParts>;
  /** requested: every model asked for, in order (for the checks); failed: the look fell back this mount. */
  state: { failed: boolean; requested: string[] };
  /** Frees every geometry built from the models (the engine's unmount). */
  dispose(): void;
}

/** The model's bytes from HERO_MODEL_DIR; a non-2xx answer is a failure. */
async function fetchModel(name: string): Promise<ArrayBuffer> {
  const r = await fetch(`${HERO_MODEL_DIR}${name}.glb`);
  if (!r.ok) throw new Error(`${HERO_MODEL_DIR}${name}.glb: HTTP ${r.status}`);
  return r.arrayBuffer();
}
/** Parses a .glb's bytes; the loader's own chunk is requested on the first call only. */
async function parseModel(buf: ArrayBuffer): Promise<THREE.Object3D> {
  const { GLTFLoader } = await import("three/addons/loaders/GLTFLoader.js");
  const g = await new GLTFLoader().parseAsync(buf, "");
  return g.scene;
}

export function createModels(fetchBytes: (name: string) => Promise<ArrayBuffer> = fetchModel): Models {
  const scenes = new Map<string, Promise<THREE.Object3D>>(), shapes = new Map<string, Promise<unknown>>(), built: THREE.BufferGeometry[] = [];
  const state = { failed: false, requested: [] as string[] };
  // Handled by whoever uses it; never an unhandled rejection.
  const quiet = <T,>(p: Promise<T>) => { p.catch(() => {}); return p; };
  function load(name: string) {
    let p = scenes.get(name);
    if (!p) { state.requested.push(name); p = quiet(fetchBytes(name).then(parseModel)); scenes.set(name, p); }
    return p;
  }
  /** make(scene) from a model, once per key (the merge is not free). */
  function shape<T>(name: string, key: string, make: (s: THREE.Object3D) => T): Promise<T> {
    const k = `${name}|${key}`;
    let p = shapes.get(k) as Promise<T> | undefined;
    if (!p) { p = quiet(load(name).then(make)); shapes.set(k, p); }
    return p;
  }
  const geo = (g: THREE.BufferGeometry) => { built.push(g); return g; };
  return {
    load,
    state,
    carParts: (id) => shape(id, "car", (s) => {
      const glass = s.getObjectByName("glass"), wheels = WHEEL_NAMES.map((n) => s.getObjectByName(n));
      if (!glass || wheels.some((w) => !w) || !s.getObjectByName("body")) throw new Error(`${id}.glb: missing its body, glass or wheel nodes`);
      const ws = wheels as THREE.Object3D[];
      return {
        body: geo(dGeo(s, { skip: (o) => dUnder(o, [glass, ...ws]) })), glass: geo(dGeo(glass, {}, s)),
        wheels: Object.fromEntries(ws.map((w, k) => [WHEEL_NAMES[k], { x: w.position.x, r: w.position.y, z: w.position.z, geo: geo(dGeo(w)) }])),
      };
    }),
    // A tree: crowns and tiers shade round (a wide crease), trunks stay crisp at the ground.
    tree: (name) => shape(name, "tree", (s) => geo(dGeo(s, { crease: 1.1 }))),
    // Trackside furniture (metres) as it was authored.
    furniture: (name) => shape(name, "furniture", (s) => geo(dGeo(s))),
    // Mount Fuji's slopes shade a little rounder.
    mountain: () => shape(DETAILED.mountainFuji, "mountain", (s) => geo(dGeo(s, { crease: 0.9 }))),
    gantry: (X) => shape("gantry", X.toFixed(4), (s) => geo(dGeo(s, { at: (o) => (o.name === "post-l" ? new THREE.Matrix4().makeTranslation(1 - X, 0, 0) : o.name === "post-r" ? new THREE.Matrix4().makeTranslation(X - 1, 0, 0) : o.name === "beam" ? new THREE.Matrix4().makeScale(X, 1, 1) : null) }))),
    dispose() { for (const g of built) g.dispose(); built.length = 0; scenes.clear(); shapes.clear(); },
  };
}
